---
- name: Another netwrok playbook
  hosts: ~^arista
  gather_facts: no

  tasks:
          - name: Harvest facts
            eos_facts:
            when: ansible_network_os == 'eos'

          - name: Push to the local system 
            copy:
                   content: "{{ ansible_facts | to_nice_json }}"
                   dest: "/home/student/mycode/{{ inventory_hostname }}.txt"
            tags:
                    - never
                    - grabfacts

          - fail:
                  msg: "FAIL. Network device lacks the correct number of interfaces."
                  when: ansible_facts.net_interfaces|length != 13      


